/** Popular industry labels for company create/import. Free text still allowed via Other. */
export const COMPANY_INDUSTRIES = [
  'Software / SaaS',
  'Financial services',
  'Healthcare',
  'Manufacturing',
  'Retail',
  'E-commerce',
  'Professional services',
  'Cybersecurity',
  'Telecommunications',
  'Media and entertainment',
  'Education',
  'Energy',
  'Logistics and transportation',
  'Real estate',
  'Insurance',
  'Government',
  'Nonprofit',
  'Hospitality',
  'Biotechnology',
  'Automotive',
] as const;

/** Well-known company website domains as suggestions. The field stays free text. */
export const POPULAR_COMPANY_DOMAINS = [
  'salesforce.com',
  'hubspot.com',
  'microsoft.com',
  'google.com',
  'amazon.com',
  'aws.amazon.com',
  'oracle.com',
  'sap.com',
  'servicenow.com',
  'snowflake.com',
  'databricks.com',
  'stripe.com',
  'slack.com',
  'zoom.us',
  'atlassian.com',
  'adobe.com',
  'nvidia.com',
  'ibm.com',
  'accenture.com',
  'deloitte.com',
] as const;
